version: '3.5'

services:
  app:
    build:
      context: ./docker/php/
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./project:/var/www/
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 8000:80
      - 443:443
    tty: true
    volumes:
      - ./project:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network
  db:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - ./project/.env
    environment:
      MYSQL_DATABASE: tree_layer_architecture
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lumen_user
      MYSQL_PASSWORD: 9x5mT7h4av]k
    networks:
      - app-network
# Docker Networks
networks:
  app-network:
    driver: bridge